name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      # - uses: Makefile/make say-hello
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: echo "Hello, World!"
      